name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AIOPS_HOST }}
        username: ${{ secrets.AIOPS_USER }}
        key: ${{ secrets.AIOPS_SSH_KEY }}
        script: |

          if [ ! -d ~/frontend-project ]; then
            git clone  https://github.com/noblehallwebsite-source/mlops-ai-service.git  ~/frontend-project
          fi

          cd ~/frontend-project

          git fetch origin
          git reset --hard origin/main

          docker build -t frontend-app .

          docker stop frontend || true
          docker rm frontend || true

          docker run -d \
            --name frontend \
            -p 127.0.0.1:3000:80 \
            frontend-app